title: "GOTM NN Training Data"
description: >
  Data for NN training from Sane et al. 2023. (Parameterizing Vertical Mixing Coefficients in the Ocean Surface Boundary Layer using Neural Networks).
  An additional text data file is available at: https://nyu1.osn.mghpcc.org/leap-pangeo-manual/GOTM/data_testing_4_paper.txt

recipes:
  - id: "raw_training"
  - id: "sf_training"
provenance:
  providers:
    - name: "Zenodo"
      description: https://zenodo.org/records/8293998
      roles:
        - archive
        - doi
  license: "Creative Commons Attribution 4.0 International"
maintainers:
  - name: "Raphael Hagen"
    github: norlandrhagen
